// Table of contents (TOC) plugin: replaces a [[toc]] or [toc] placeholder on its own
// line with a TOC nested by heading level
// TOC links point at the ids generated by the anchors plugin, so this plugin must be
// registered after headingAnchors
// Heading plain text comes from inline.content (anchors only inserts into children,
// leaving content untouched), so it carries no anchor symbol

const TOC_RE = /^(\[\[toc\]\]|\[toc\])$/i;

// Whether the paragraph is a TOC placeholder: paragraph_open + inline (content is
// exactly the marker) + paragraph_close
function isTocMarker(tokens, i) {
  return (
    tokens[i].type === 'paragraph_open' &&
    tokens[i + 1]?.type === 'inline' &&
    tokens[i + 2]?.type === 'paragraph_close' &&
    TOC_RE.test(tokens[i + 1].content.trim())
  );
}

function collectHeadings(tokens) {
  const headings = [];
  for (let i = 0; i < tokens.length; i++) {
    if (tokens[i].type !== 'heading_open') continue;
    const inline = tokens[i + 1];
    if (inline?.type !== 'inline') continue;
    headings.push({
      level: Number(tokens[i].tag.slice(1)),
      id: tokens[i].attrGet('id') || '',
      text: inline.content,
    });
  }
  return headings;
}

// Build a nested <ul> TOC from the flat heading list (with levels); deeper headings
// nest inside the previous item
function tocHtml(headings, escapeHtml) {
  if (!headings.length) return '<nav class="table-of-contents"></nav>\n';
  const base = Math.min(...headings.map((h) => h.level));
  const parts = ['<ul>'];
  let level = base;
  let openLi = false;
  for (const h of headings) {
    if (h.level > level) {
      for (let l = level; l < h.level; l++) parts.push('<ul>');
    } else {
      if (openLi) parts.push('</li>');
      for (let l = level; l > h.level; l--) parts.push('</ul>', '</li>');
    }
    level = h.level;
    parts.push(`<li><a href="#${h.id}">${escapeHtml(h.text)}</a>`);
    openLi = true;
  }
  if (openLi) parts.push('</li>');
  for (let l = level; l > base; l--) parts.push('</ul>', '</li>');
  parts.push('</ul>');
  return `<nav class="table-of-contents">\n${parts.join('\n')}\n</nav>\n`;
}

/**
 * markdown-it plugin: at the end of the core chain (once headings have ids), replace
 * TOC placeholders with the table of contents
 * @param {import('markdown-it')} md
 */
export function tableOfContents(md) {
  md.core.ruler.push('table_of_contents', (state) => {
    const tokens = state.tokens;
    // First scan for a placeholder; bail out early when there is none, to avoid
    // extra work on documents without a TOC
    let found = false;
    for (let i = 0; i + 2 < tokens.length; i++) {
      if (isTocMarker(tokens, i)) {
        found = true;
        break;
      }
    }
    if (!found) return;

    const html = tocHtml(collectHeadings(tokens), md.utils.escapeHtml);
    // Replace each placeholder paragraph (3 tokens) with a single html_block; after
    // splice, i points at the new token, so the scan continues onward
    for (let i = 0; i + 2 < tokens.length; i++) {
      if (!isTocMarker(tokens, i)) continue;
      const token = new state.Token('html_block', '', 0);
      token.content = html;
      token.block = true;
      tokens.splice(i, 3, token);
    }
  });
}
